# Generated by Django 4.2.2 on 2023-06-16 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("AreYouIdol", "0009_alter_upload_img"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Upload",
        ),
    ]
